[dev]
command = "hugo serve"
targetPort = 1313
port = 8888
publish = "public"
autoLaunch = false

[build.environment]
HUGO_VERSION = "0.161.0"
NODE_VERSION = "18"

[build]
# Can't set this here since I need it to be overrideable from the web UI for drafts.msfjarvis.dev
# command = "hugo --gc --minify && npx -y pagefind --site public"
publish = "public"

[[edge_functions]]
path = "/*"
function = "root"

[[edge_functions]]
function = "webfinger"
path = "/.well-known/webfinger"

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200

[[redirects]]
from = "/posts/:slug.txt"
to = "/posts/:slug/index.txt"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "script-src identity.netlify.com stats01.msfjarvis.dev drafts.msfjarvis.dev msfjarvis.dev utteranc.es 'unsafe-inline' 'wasm-unsafe-eval'; object-src 'none'; connect-src msfjarvis.dev drafts.msfjarvis.dev 07d4cd9cc7e8077fcafc5dd2fc30391b.r2.cloudflarestorage.com webmentions-server.tiger-shark.workers.dev stats01.msfjarvis.dev;"
Referrer-Policy = 'strict-origin-when-cross-origin'
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = '1; mode=block'

[[headers]]
for = "/admin/*"
[headers.values]
Content-Security-Policy = "script-src identity.netlify.com unpkg.com msfjarvis.dev drafts.msfjarvis.dev 'unsafe-inline' 'unsafe-eval'"
Referrer-Policy = 'strict-origin-when-cross-origin'
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = '1; mode=block'

[[headers]]
for = "/pretty-feed-v3.xsl"
[headers.values]
Content-Type = "application/xml; charset=utf-8"

[[headers]]
for = "/posts/*.txt"
[headers.values]
Content-Type = "text/plain; charset=utf-8"

[[headers]]
for = "/posts/*/*.txt"
[headers.values]
Content-Type = "text/plain; charset=utf-8"
