[dev]
  command = "hugo serve"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[build.environment]
  HUGO_VERSION = "0.122.0"
  NODE_VERSION = "18"

[[edge_functions]]
path = "/*"
function = "root"


[[edge_functions]]
function = "webfinger"
path = "/.well-known/webfinger"

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200
