[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.106.0"

[[edge_functions]]
path = "/*"
function = "root"


[[edge_functions]]
function = "webfinger"
path = "/.well-known/webfinger"
