[dev]
command = "hugo serve"
targetPort = 1313
port = 8888
publish = "public"
autoLaunch = false

[build.environment]
HUGO_VERSION = "0.150.0"
NODE_VERSION = "18"

[[edge_functions]]
path = "/*"
function = "root"

[[edge_functions]]
function = "webfinger"
path = "/.well-known/webfinger"

[[redirects]]
from = "/robots.txt"
to = "/robots.txt"
status = 200

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200

[[headers]]
for = "/*"
[headers.values]
Content-Security-Policy = "script-src identity.netlify.com stats.msfjarvis.dev msfjarvis.dev utteranc.es 'unsafe-inline'"
Referrer-Policy = 'strict-origin-when-cross-origin'
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = '1; mode=block'

[[headers]]
for = "/admin/*"
[headers.values]
Content-Security-Policy = "script-src identity.netlify.com unpkg.com 'unsafe-inline' 'unsafe-eval'"
Referrer-Policy = 'strict-origin-when-cross-origin'
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = '1; mode=block'

[[headers]]
for = "/pretty-feed-v3.xsl"
[headers.values]
Content-Type = "application/xml; charset=utf-8"
