[build]
  command = "hugo"
  publish = "public"

[dev]
  command = "hugo serve"
  targetPort = 1313
  port = 8888
  publish = "public"
  autoLaunch = false

[build.environment]
  HUGO_VERSION = "0.109.0"

[[edge_functions]]
path = "/*"
function = "root"


[[edge_functions]]
function = "webfinger"
path = "/.well-known/webfinger"
