packages:
  - "."
overrides:
  satteri: ^0.9.5
patchedDependencies:
  "@mermanjs/web@0.7.0": patches/@mermanjs__web@0.7.0.patch
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "astro"
  - "@astrojs/cloudflare"
  - "@astrojs/markdown-satteri"
  - "@xingwangzhe/satteri-mermaid"
  - "@sveltia/cms"
blockExoticSubdeps: true
trustPolicy: no-downgrade
enableGlobalVirtualStore: false
trustPolicyExclude:
  - "chokidar@4.0.3"
