packages:
  - "."
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  # keep-sorted start
  - "@astrojs/cloudflare"
  - "@astrojs/compiler-binding"
  - "@astrojs/compiler-binding-android-arm64"
  - "@astrojs/compiler-binding-darwin-arm64"
  - "@astrojs/compiler-binding-darwin-x64"
  - "@astrojs/compiler-binding-linux-arm64-gnu"
  - "@astrojs/compiler-binding-linux-arm64-musl"
  - "@astrojs/compiler-binding-linux-x64-gnu"
  - "@astrojs/compiler-binding-linux-x64-musl"
  - "@astrojs/compiler-binding-wasm32-wasi"
  - "@astrojs/compiler-binding-win32-arm64-msvc"
  - "@astrojs/compiler-binding-win32-x64-msvc"
  - "@astrojs/compiler-rs"
  - "@astrojs/internal-helpers"
  - "@astrojs/markdown-satteri"
  - "@astrojs/underscore-redirects"
  - "@cloudflare/unenv-preset"
  - "@cloudflare/workerd-darwin-64"
  - "@cloudflare/workerd-darwin-arm64"
  - "@cloudflare/workerd-linux-64"
  - "@cloudflare/workerd-linux-arm64"
  - "@cloudflare/workerd-windows-64"
  - "@jsr/msfjarvis__prettier-plugin-keep-sorted@0.1.0"
  - "@sveltia/cms"
  - "@xingwangzhe/satteri-mermaid"
  - astro
  - miniflare
  - workerd
  - wrangler
# keep-sorted end
blockExoticSubdeps: true
trustPolicy: no-downgrade
enableGlobalVirtualStore: false
trustPolicyExclude:
  - "chokidar@4.0.3"
