packages:
  - "."
overrides:
  satteri: ^0.9.5
patchedDependencies:
  "@mermanjs/web@0.7.0": patches/@mermanjs__web@0.7.0.patch
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "astro"
  - "@astrojs/cloudflare"
  - "@astrojs/internal-helpers"
  - "@astrojs/markdown-satteri"
  - "@astrojs/underscore-redirects"
  - "@cloudflare/workerd-darwin-64"
  - "@cloudflare/workerd-darwin-arm64"
  - "@cloudflare/workerd-linux-64"
  - "@cloudflare/workerd-linux-arm64"
  - "@cloudflare/workerd-windows-64"
  - "miniflare"
  - "@sveltia/cms"
  - "workerd"
  - "wrangler"
  - "@xingwangzhe/satteri-mermaid"
blockExoticSubdeps: true
trustPolicy: no-downgrade
enableGlobalVirtualStore: false
trustPolicyExclude:
  - "chokidar@4.0.3"
