name = "msfjarvis-dev-staging"
type = "webpack"
webpack_config = "webpack.config.js"
workers_dev = false
route = "staging.msfjarvis.dev/*"
vars = { BASE_URL = "https://staging.msfjarvis.dev/" }

[site]
bucket = "./public"
entry-point = "workers-site"

[env.production]
name = "msfjarvis-dev-prod"
route = "msfjarvis.dev/*"
vars = { BASE_URL = "https://msfjarvis.dev/" }
