name = "msfjarvis-dev-staging"
workers_dev = false
route = "drafts.msfjarvis.dev/*"
vars = { BASE_URL = "https://drafts.msfjarvis.dev/" }
compatibility_date = "2021-11-08"
kv_namespaces = [
  { binding = "NAMESPACE", id = "43d755465f4642ccb30b1bdce031d1da", preview_id = "d2c0bff9f5584c938131063c9a702611" },
]
main = "dist/worker.production.js"

[build]
command = "yarn run build"

[site]
bucket = "./public"

[env.production]
name = "msfjarvis-dev-prod"
route = "msfjarvis.dev/*"
vars = { BASE_URL = "https://msfjarvis.dev/" }
kv_namespaces = [
  { binding = "NAMESPACE", id = "303799a857b0490482dabaf6c9ed0af8" }
]
