baseurl = "https://www.example.com"
title = "yii.im"
theme = "vec"
languageCode = "en-us"
paginate = 10
disqusShortname = "yiiim"
googleAnalytics = "UA-57408564-1"

[menu]
  # Shown in the side menu.
  [[menu.main]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.main]]
    name = "contact"
    weight = 1
    url = "/contact"
  [[menu.main]]
    name = "faq"
    weight = 2
    url = "/faq"
    
[params]
  Keywords = "key, 关键字, キーワード"
  Description = "There are some words to describe your site"
  Avater = "img/avatar.jpg"
  SelfIntro = "Just a worm, seek for true, live in shadow, no more..." 
  Email = "yiichou@gmail.com"
  
  GithubID = "Your Github ID"
  TwitterID = "Your Twitter ID"
  FacebookID = "Your Facebook ID"
  LinkedInID = "Your LinkedIn ID"
  GoogleplusID = "Your Googleplus ID"