// Generated by scripts/refresh-mastodon-snapshots.mjs — do not edit by hand.
// Regenerate with: pnpm mastodon:refresh
import type { MastodonStatus } from "../lib/mastodon.ts";

export const mastodonSnapshots = {
  "https://fantastic.earth/@msfjarvis/117284587802078178": {
    canonicalUrl: "https://fantastic.earth/@msfjarvis/117284587802078178",
    paragraphs: [
      "New facts have come to light in this investigation and the updated hypothesis now states that I am the world's greatest idiot.",
      "Turns out I have been typing in my PIN via muscle memory instead of actual memorization for the past 18 months, and the actual PIN is one digit off than what I had intended/remembered. When I consciously think about it I get the PIN wrong, when I remove my brain from the equation I get it right.",
      "The human brain is a beautiful enigma.",
    ],
    createdAt: "2026-09-17T04:53:05.553Z",
    author: {
      displayName: "Harsh Shandilya",
      account: "@msfjarvis@fantastic.earth",
    },
    images: [],
    attachments: [],
  },
  "https://infosec.exchange/@0xabad1dea/116900098449254586": {
    canonicalUrl: "https://infosec.exchange/@0xabad1dea/116900098449254586",
    paragraphs: [
      "Odin got a bit hyper this morning when he realized that mommy had *not* snuck out the door at the crack of dawn this time",
    ],
    createdAt: "2026-07-11T07:12:23.625Z",
    author: {
      displayName: "abadidea",
      account: "@0xabad1dea@infosec.exchange",
    },
    images: [
      {
        url: "https://media.infosec.exchange/infosec.exchange/media_attachments/files/116/900/098/232/693/858/original/306f8447de78adee.jpeg",
        alt: "Odin the Newfie full of love, wonder and drool ",
      },
    ],
    attachments: [],
  },
  "https://infosec.exchange/@0xabad1dea/116946074763792559": {
    canonicalUrl: "https://infosec.exchange/@0xabad1dea/116946074763792559",
    paragraphs: [
      "Public Transport Odin on his way to say goodbye to the Jesuit scholars before they return to Rome",
    ],
    createdAt: "2026-07-19T10:04:46.508Z",
    author: {
      displayName: "abadidea",
      account: "@0xabad1dea@infosec.exchange",
    },
    images: [
      {
        url: "https://media.infosec.exchange/infosec.exchange/media_attachments/files/116/946/074/281/497/258/original/b94153dd391a8c26.jpeg",
        alt: "Odin the Newfie pleased about riding the Amsterdam tram ",
      },
      {
        url: "https://media.infosec.exchange/infosec.exchange/media_attachments/files/116/946/074/555/145/173/original/68f7bada6492ec33.jpeg",
        alt: "Odin the Newfie loitering at the entrance to Vondelpark ",
      },
    ],
    attachments: [],
  },
  "https://infosec.exchange/@0xabad1dea/116980897659510296": {
    canonicalUrl: "https://infosec.exchange/@0xabad1dea/116980897659510296",
    paragraphs: [
      "Someone needed an extra big brushie and wasn’t too thrilled about it",
    ],
    createdAt: "2026-07-25T13:40:41.730Z",
    author: {
      displayName: "abadidea",
      account: "@0xabad1dea@infosec.exchange",
    },
    images: [
      {
        url: "https://media.infosec.exchange/infosec.exchange/media_attachments/files/116/980/896/851/127/222/original/9b70721014bfd3f1.jpeg",
        alt: "Me sitting on the floor next to Odin the Newfie, holding an enormous quantity of black fur ",
      },
      {
        url: "https://media.infosec.exchange/infosec.exchange/media_attachments/files/116/980/897/378/887/974/original/8f7032a3ff6e7912.jpeg",
        alt: "Odin making his best attempt at an intimidating face at mommy ",
      },
    ],
    attachments: [],
  },
} satisfies Record<string, MastodonStatus>;
