name: Hugo deployment test

on:
  push:
    branches-ignore:
    - gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.2
      with:
        hugo-version: '0.59.1'
        extended: true

    - name: Build
      run: hugo --minify -DEFb=https://msfjarvis.github.io/msfjarvis.website

    - name: Deploy
      uses: docker://peaceiris/gh-pages:latest
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public

    - name: Audit live URL
      uses: docker://jakejarvis/lighthouse-action:latest
      with:
        url: 'https://msfjarvis.github.io/msfjarvis.website/'

    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
