name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'
permissions:
  contents: write
jobs:
  update-flake-lock:
    uses: msfjarvis/shared-workflows/.github/workflows/update-flake-lock.yml@170448569b6e8658437bc48d849272fd7e47a806 # main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
