name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'
permissions:
  contents: write
jobs:
  update-flake-lock:
    uses: msfjarvis/shared-workflows/.github/workflows/update-flake-lock.yml@d20c33f82d94ce8f19fe389b67dc348bf671f07b # main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
