name: Update flake.lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 0'
permissions:
  contents: write
jobs:
  update-flake-lock:
    uses: msfjarvis/shared-workflows/.github/workflows/update-flake-lock.yml@66a34efd7dc06329c4add03a397ac50c030e8804 # main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
