name: Lighthouse testing

on:
  push:
    branches:
    - src

jobs:
  lighthouse-test:
    runs-on: ubuntu-18.04
    steps:
    - name: Wait for deployment to finish
      run: sleep 10
    - name: Audit URL using Lighthouse
      uses: jakejarvis/lighthouse-action@master
      with:
        url: 'https://msfjarvis.dev/'
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'
